name: "nasCloud4HAaddon"
description: "WireGuard-based remote access to Home Assistant via haos.app"
version: "0.1.0"
slug: "nascloud4haaddon"
init: false
startup: services
arch:
  - aarch64
  - armv7

hassio_api: true

privileged:
  - NET_ADMIN

devices:
  - /dev/net/tun

options:
  nasweb_cloud: false
  nasweb_cloud_subdomain: ""
  nasweb_cloud_port: 8123

schema:
  nasweb_cloud: bool
  nasweb_cloud_subdomain: str?
  nasweb_cloud_port: int(1,65535)
