name: "nasCloud4HAaddon"
description: "WireGuard-based remote access to Home Assistant via haos.app"
version: "0.1.0"
slug: "nascloud4haaddon"
init: false
startup: services
arch:
  - amd64
  - aarch64
  - armv7

hassio_api: true

privileged:
  - NET_ADMIN

devices:
  - /dev/net/tun

options:
  nasweb_cloud: false
  nasweb_cloud_subdomain: ""
  nasweb_cloud_port: 8123
  cloud_public_domain: "haos.app"
  cloud_health_interval: 300
  cloud_auth_user: ""
  cloud_auth_pass: ""
  cloud_client_id: ""
  cloud_server_url: ""
  cloud_server_ip: ""

schema:
  nasweb_cloud: bool
  nasweb_cloud_subdomain: str?
  nasweb_cloud_port: int(1,65535)
  cloud_public_domain: str?
  cloud_health_interval: int(60,3600)
  cloud_auth_user: str?
  cloud_auth_pass: password?
  cloud_client_id: str?
  cloud_server_url: str?
  cloud_server_ip: str?
